// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Flexbox: typeof import('./src/components/Flexbox.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Space: typeof import('./src/components/Space.vue')['default']
    TextSizeColor: typeof import('./src/components/TextSizeColor.vue')['default']
  }
}
